# Generated by Django 5.2 on 2025-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e2ee_public_key',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
