# Generated by Django 5.2 on 2025-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_e2ee_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e2ee_public_key',
            field=models.JSONField(blank=True, null=True, unique=True),
        ),
    ]
