services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - './frontend/vite.config.js:/app/vite.config.js'
      - './frontend/src:/app/src'
      - './frontend/index.html:/app/index.html'
    ports:
      - "5173:5173"